#!/bin/sh
set -xev

UNREAL=$HOME/unrealircd
BACKUP=$UNREAL.backup
SOURCE=$UNREAL.source

#LATEST=$(curl -s https://www.unrealircd.org/downloads/list.json | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^version/ {print $2}' | sed 's/\(^"\|"$\)//g')

update_source() {
	wget -O $SOURCE.tar.gz https://www.unrealircd.org/downloads/unrealircd-latest.tar.gz
	tar -xvf $SOURCE.tar.gz --one-top-level --strip-components=1
	rm $SOURCE.tar.gz
	sed -i 's/NICKNAMEHISTORYLENGTH="2000"/NICKNAMEHISTORYLENGTH="100"/g' $SOURCE/Config
	sed -i 's/REMOTEINC=""/REMOTEINC="1"/g' $SOURCE/Config
	sed -i 's/PREFIXAQ="1"/PREFIXAQ="0"/g' $SOURCE/Config
	sed -i 's/SHOWLISTMODES="1"/SHOWLISTMODES="0"/g' $SOURCE/Config
	sed -i 's;//#undef FAKELAG_CONFIGURABLE;#define FAKELAG_CONFIGURABLE;g' $SOURCE/include/config.h
	sed -i 's_\t\t\tsendnotice(acptr, "*** You were forced to join %s", jbuf);_\t\t\t//sendnotice(acptr, "*** You were forced to join %s", jbuf);_g' $SOURCE/src/modules/m_sapart.c
	rm -r $SOURCE/doc/conf/aliases $SOURCE/doc/conf/examples $SOURCE/doc/conf/help
	rm -r $SOURCE/doc/conf/*.conf
	cp $HOME/dev/git/supernets/unrealircd/doc/conf/*.conf $SOURCE/doc/conf/
	cp $HOME/dev/git/supernets/unrealircd/src/ssl.cnf $SOURCE/src/ssl.cnf
	echo "edit your Makefile.in"
}

deploy() {
	git clone --depth 1 https://github.com/supernets/unrealircd.git $SOURCE
	cd $SOURCE && echo -e "\n" | ./Config -nointro && make && make install && cd $HOME && rm -rf $SOURCE
	rm $UNREAL/conf/*.conf
	read -p "Link Name: " NAME
	SID=$(cat /dev/urandom | tr -dc '0-9' | fold -w 256 | head -n 1 | head --bytes 1)$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 2 | head -n 1)
	echo "[NOTE] - Your remote include should be in http(s)://USERNAME:PASSWORD@HOSTNAME:PORT format"
	read -p "Remote Include: " REMOTE
	for item in aliases badwords except help ircd modules opers spamfilter; do echo $REMOTE/$item.conf >> $UNREAL/conf/unrealircd.conf; done
	echo "me { name \"$NAME.supernets.org\"; info \"SuperNETs IRC Network\"; sid $SID; }" >> $UNREAL/conf/unrealircd.conf
	SPKI=$($UNREAL/unrealircd spkifp | sed -n 5p)
	echo -e "\nAdd the following line into the hub\'s links.conf file for this link:\n$SPKI"
	$UNREAL/unrealircd start &
}

update() {
	[ ! -z $(screen -ls | grep ircdwatchdog) ] && screen -S ircdwatchdog -X quit
	[ ! -z $(abduco     | grep ircdwatchdog) ] && pkill -9 $(abduco | grep ircdwatchdog | awk '{print $4}')
	mkdir $BACKUP
	cp $UNREAL/conf/unrealircd.conf $BACKUP && cp $UNREAL/conf/ssl/server.*.pem $BACKUP
	#cp $UNREAL/conf/links.conf $BACKUP && cp $UNREAL/conf/modules.conf $BACKUP && cp $UNREAL/conf/opers.conf $BACKUP
	$UNREAL/unrealircd stop
	rm -rf $UNREAL
	git clone --depth 1 https://github.com/supernets/unrealircd.git $SOURCE
	cd $SOURCE && echo -e "\n" | ./Config -nointro && make && make install && cd $HOME && rm -rf $SOURCE
	mv $BACKUP/*.conf $UNREAL/conf/ && mv $BACKUP/server.*.pem $UNREAL/conf/ssl
	rm -r $BACKUP
	$UNREAL/unrealircd start
	watchdog
}

watchdog() {
	if command -v abduco >/dev/null 2>&1; then
		abduco -fnr ircdwatchdog     bash -c "while true; do [ ! -f $HOME/unrealircd/data/unrealircd.pid ] && $HOME/unrealircd/unrealircd start; sleep 15; done"
	elif command -v screen >/dev/null 2>&1; then
		screen -S   ircdwatchdog -dm bash -c "while true; do [ ! -f $HOME/unrealircd/data/unrealircd.pid ] && $HOME/unrealircd/unrealircd start; sleep 15; done"
	else
		echo "[!] - install abduco or screen"
	fi
}

[ $1 = "deploy"   ] && deploy   && exit 1
[ $1 = "update"   ] && update   && exit 1
[ $1 = "watchdog" ] && watchdog && exit 1