#!/bin/sh
UNREAL=$HOME/unrealircd
BACKUP=$UNREAL.backup
SOURCE=$UNREAL.source

deploy() {
	git clone --depth 1 https://github.com/supernets/unrealircd.git $SOURCE
	cd $SOURCE && echo -e "\n" | ./Config -nointro && make && make install && cd $HOME && rm -rf $SOURCE
	rm $UNREAL/conf/*.conf
	read -p "Link Name: " NAME
	SID=$(cat /dev/urandom | tr -dc '0-9' | fold -w 256 | head -n 1 | head --bytes 1)$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 2 | head -n 1)
	read -p "Remote Include: " REMOTE
	for item in badwords except ircd modules opers spamfilter; do echo $REMOTE/$item.conf >> $UNREAL/conf/unrealircd.conf; done
	echo "me { name \"$NAME.supernets.org\"; info \"SuperNETs IRC Network\"; sid $SID; }" >> $UNREAL/conf/unrealircd.conf
	SPKI=$($UNREAL/unrealircd spkifp | sed -n 5p)
	echo -e "\nAdd the following line into the hub\'s links.conf file for this link:\n$SPKI"
	$UNREAL/unrealircd start &
	crontab -l | { cat; echo "*/5 * * * * $HOME/unrealircd/unrealircd croncheck"; } | crontab -
	crontab -l | { cat; echo "@reboot $HOME/unrealircd/unrealircd croncheck";     } | crontab -
}

latest() {
	local CURRENT=$($UNREAL/unrealircd version | awk '{print $NF}')
	local LATEST=$(curl -s https://www.unrealircd.org/downloads/list.json | jq '[.[]][1].Stable.type')
	[ $CURRENT != $LATEST ] && echo "new version available: $LATEST"
}

update() {
	mkdir $BACKUP && cp $UNREAL/conf/unrealircd.conf $BACKUP && cp $UNREAL/conf/tls/server.*.pem $BACKUP
	$UNREAL/unrealircd stop && rm -rf $UNREAL
	git clone --depth 1 https://github.com/supernets/unrealircd.git $SOURCE
	cd $SOURCE && echo -e "\n" | ./Config -nointro && make && make install && cd $HOME && rm -rf $SOURCE
	rm $UNREAL/conf/*.conf && mv $BACKUP/unrealircd.conf $UNREAL/conf/ && mv $BACKUP/server.*.pem $UNREAL/conf/tls && rm -r $BACKUP
	$UNREAL/unrealircd start
}

[ $1 = "deploy" ] && deploy && exit 1
[ $1 = "latest" ] && latest && exit 1
[ $1 = "update" ] && update && exit 1
