#!/bin/sh
start() {
	pkill -9 abduco && pkill -9 python
	cd $HOME/bots              && abduco -fnr FUCKYOU      python 5000.py         && sleep 1
	cd $HOME/bots/anythinggoes && abduco -fnr anythinggoes python anythinggoes.py && sleep 1
	cd $HOME/bots              && abduco -fnr cancer       python cancer.py       && sleep 1
	cd $HOME/bots/dickserv     && abduco -fnr dickserv     python dickserv.py     && sleep 1
	cd $HOME/bots/irccex/efnet && abduco -fnr irccex-efnet python irccex.py       && sleep 1
	cd $HOME/bots/irccex/super && abduco -fnr irccex-super python irccex.py       && sleep 1
	cd $HOME/bots              && abduco -fnr limitserv    python limitserv.py    && sleep 1
	cd $HOME/bots/scroll       && abduco -fnr scroll       python scroll.py       && sleep 1
	cd $HOME/bots              && abduco -fnr spiderweb    python spiderweb.py
}

get() {
	mkdir $HOME/bots
	wget -O $HOME/bots/5000.py https://raw.githubusercontent.com/acidvegas/trollbots/master/5000.py
	mkdir -P $HOME/bots/anythinggoes/data
	wget -O $HOME/bots/anythinggoes/anythinggoes.py https://github.com/acidvegas/random/blob/master/irc/anythinggoes/anythinggoes.py
	wget -O $HOME/bots/anythinggoes/data/banana.txt https://github.com/acidvegas/random/blob/master/irc/anythinggoes/data/banana.txt
	wget -O $HOME/bots/anythinggoes/data/crab.txt https://github.com/acidvegas/random/blob/master/irc/anythinggoes/data/crab.txt
	wget -O $HOME/bots/anythinggoes/data/crate.txt https://github.com/acidvegas/random/blob/master/irc/anythinggoes/data/crate.txt
	wget -O $HOME/bots/anythinggoes/data/worms.txt https://github.com/acidvegas/random/blob/master/irc/anythinggoes/data/worms.txt
	wget -O $HOME/bots/cancer.py https://raw.githubusercontent.com/acidvegas/random/master/irc/cancer.py
	git clone --depth 1 https://github.com/acidvegas/dickserv.git $HOME/bots/dickserv
	mkdir $HOME/bots/irccex
	git clone --depth 1 https://github.com/pumpcoin/irccex.git $HOME/bots/irccex/irccex-efnet
	git clone --depth 1 https://github.com/pumpcoin/irccex.git $HOME/bots/irccex/irccex-super
	wget -O $HOME/bots/limitserv.py https://raw.githubusercontent.com/acidvegas/limitserv/master/limitserv.py
	git clone --depth 1 https://github.com/ircart/scroll.git $HOME/bots/scroll
	rm -r $HOME/bots/scroll/scroll/data/art
	git clone --depth 1 https://github.com/ircart/ircart.git $HOME/bots/scroll/scroll/data/art
	wget -O $HOME/bots/spiderweb.py https://raw.githubusercontent.com/acidvegas/trollbots/master/spiderweb.py
}

[ $1 = "start" ] && start && exit 1
[ $1 = "get"   ] && get   && exit 1